# -*- coding: utf-8 -*-
"""xls to xml parser

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1f8qkHKUzQLdy-L9txKaAKEy32UMo-oRJ
"""

from openpyxl import load_workbook
from yattag import Doc, indent

#open excel namanya contohsoal ganti path sesuai lokasi folder
wb = load_workbook("/content/contohsoal.xlsx")
ws = wb.worksheets[0]

xml_header = '<?xml version="1.0" encoding="UTF-8"?>'
xml_schema = '<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema"></xs:schema>'

#set xml header
doc, tag, text = Doc().tagtext()
doc.asis(xml_header)
doc.asis(xml_schema)
with tag('BankSoal'):
    # Pake ws.max_row untuk mengambil data baris max rows sesuai kebutuhan soal
    for row in ws.iter_rows(min_row=2, max_row=5, min_col=1, max_col=5):
        row = [cell.value for cell in row]
        with tag("Soal"):
            with tag("soal"):
                text(row[0])
            with tag("jawaban1"):
                text(row[1])
            with tag("jawaban2"):
                text(row[2])
            with tag("jawaban3"):
                text(row[3])
            with tag("jawaban4"):
                text(row[4])

result = indent(
    doc.getvalue(),
    indentation = '    ',
    indent_text = True
)
print(result)

with open("parsersoal.xml", "w") as f:
    f.write(result)